version: '3.7'

services:
    nginx:
        image: nginx:1.23.0
        container_name: nginx
        restart: always
        environment:
            - TZ=Asia/Taipei
            - MACHINE_HOST_NAME=${MACHINE_HOST_NAME}
        volumes:
            - ./.docker/nginx/default.template:/etc/nginx/conf.d/default.template:ro
            - ./.docker/mkcert/ray.104.com.tw+5.pem:/etc/ssl/certs/ray.104.com.tw+5.pem
            - ./.docker/mkcert/ray.104.com.tw+5-key.pem:/etc/ssl/private/ray.104.com.tw+5-key.pem
        ports:
            - "80:80"
            - "443:443"
        logging:
            driver: "none"
        command: /bin/bash -c "envsubst '$${MACHINE_HOST_NAME}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    api:
        image: php:8.2.8-fpm
        container_name: api
        restart: always
        environment:
            - TZ=Asia/Taipei
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        expose:
            - "8000"
        command: >
            bash -c "php artisan --host=0.0.0.0 --port=8000 serve"
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.16.100.0/24
